apiVersion: v1
kind: Service
metadata:
  labels:
    app: react-frontend
  name: react-frontend
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: react-frontend