apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: react-frontend
  name: react-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
      - name: react-frontend
        image: "bikkrl/sdn-repo:react-app"
        ports:
        - name: http
          containerPort: 8080